services:
  - type: web
    name: vbrick-gtm-dashboard
    runtime: docker
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

